package com.project.fflb.dbo;

public class FerrariCarList {
    static String[] ferrariCars = {
            "Ferrari 125 S",
            "Ferrari 166 Inter",
            "Ferrari 195 Inter",
            "Ferrari 212 Inter",
            "Ferrari 250 GTO",
            "Ferrari 250 GT Lusso",
            "Ferrari 275 GTB",
            "Ferrari 330 P3",
            "Ferrari 365 GTB/4",
            "Ferrari Dino 206 GT",
            "Ferrari Dino 246 GT",
            "Ferrari 308 GTB",
            "Ferrari 308 GTS",
            "Ferrari 328 GTB",
            "Ferrari 328 GTS",
            "Ferrari 348 TB",
            "Ferrari 348 TS",
            "Ferrari F40",
            "Ferrari 456 GT",
            "Ferrari 512 TR",
            "Ferrari 512 BB",
            "Ferrari 550 Maranello",
            "Ferrari 575M Maranello",
            "Ferrari 599 GTB Fiorano",
            "Ferrari F50",
            "Ferrari Enzo",
            "Ferrari FXX",
            "Ferrari 612 Scaglietti",
            "Ferrari F430",
            "Ferrari F430 Scuderia",
            "Ferrari 458 Italia",
            "Ferrari 458 Spider",
            "Ferrari 488 GTB",
            "Ferrari 488 Spider",
            "Ferrari LaFerrari",
            "Ferrari GTC4Lusso",
            "Ferrari Portofino",
            "Ferrari F8 Tributo",
            "Ferrari Roma",
            "Ferrari SF90 Stradale",
            "Ferrari Monza SP1",
            "Ferrari Monza SP2",
            "Ferrari 296 GTB",
            "Ferrari Purosangue",
            "Ferrari 400 Superamerica",
            "Ferrari 410 Superamerica",
            "Ferrari 365 GT4 2+2",
            "Ferrari 412",
            "Ferrari Mondial",
            "Ferrari Testarossa",
            "Ferrari 348 Spider",
            "Ferrari 360 Modena",
            "Ferrari 360 Spider",
            "Ferrari 360 Challenge Stradale",
            "Ferrari 430 Scuderia Spider 16M",
            "Ferrari California",
            "Ferrari California T",
            "Ferrari 812 Superfast",
            "Ferrari 812 GTS",
            "Ferrari J50",
            "Ferrari SP38",
            "Ferrari SP1",
            "Ferrari SP2",
            "Ferrari F12berlinetta",
            "Ferrari F12tdf",
            "Ferrari 330 P4",
            "Ferrari 512 S",
            "Ferrari 365 GTB/4 Daytona",
            "Ferrari 488 Pista",
            "Ferrari 488 Pista Spider",
            "Ferrari Daytona SP3",
            "Ferrari FXX-K",
            "Ferrari FXX-K Evo",
            "Ferrari P80/C",
            "Ferrari 296 GTS",
            "Ferrari SP48 Unica",
            "Ferrari Omologata",
            "Ferrari BR20",
            "Ferrari 812 Competizione",
            "Ferrari 812 Competizione A",
            "Ferrari SF90 Spider",
            "Ferrari Icona Series",
            "Ferrari SP3JC"
    };

    public static String[] getCars() {
        return ferrariCars;
    }
}
